services:
  mysql:
    image: mysql:8.0
    container_name: workout-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - workout-network

  backend:
    build: ./backend
    container_name: workout-backend
    restart: unless-stopped
    depends_on:
      - mysql
    environment:
      PORT: 3000
      DB_HOST: mysql
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
    ports:
      - "3000:3000"
    networks:
      - workout-network

  frontend:
    build: ./frontend #folder name for client
    container_name: workout-frontend
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "8080:80"
    networks:
      - workout-network

volumes:
  mysql-data:

networks:
  workout-network:
    driver: bridge
